### PR TITLE
Add `csexec-loader` for ppc64le

### PR DESCRIPTION
**Pull request by lzaoral**

### CODE REVIEW

**Comment by lzaoral** [comment]
It looks like the previous run failed with some internal failure in COPR.

**Comment by lzaoral** [comment]
Hmm, same error. @kdudka any idea what's going on here? https://copr.fedorainfracloud.org/coprs/packit/csutils-cswrap-14/build/3811669/

**Comment by kdudka** [comment]
It definitely does **not** look like cswrap's mistake :-)
```
[2022-03-22 08:49:35,484][ ERROR][PID:3618606] Unexpected exception (in /usr/lib/python3.10/site-packages/copr_backend/sign.py:208)
```
I would try to re-schedule it a few hours later.

**Comment by lzaoral** [comment]
A single build I've submitted locally have just succeeded so I'm going to restart the jobs once again.

**Comment by lzaoral** [comment]
The CI is green!

**Review by kdudka — APPROVED** [review]

**Pull request merged**
